run_id: full

season:
  start_month: 7
  start_day: 1
  end_month: 4
  end_day: 1
  # use all data
  first_year: 2009
  last_year: 2022

# prediction features
groups: [season, geography, season_geo]

# include all geographies

models:
  - name: LPLModel
    seed: 42
    params:
      muA_shape1: 100.0
      muA_shape2: 180.0
      sigmaA_rate: 80.0
      tau_shape1: 100.0
      tau_shape2: 225.0
      K_shape: 150.0
      K_rate: 6.0
      muM_shape: 2.0
      muM_rate: 25.0
      sigmaM_rate: 80.0
      D_shape: 1000
      D_rate: 3.0

mcmc:
  num_warmup: 1000
  num_samples: 1000
  num_chains: 4
  progress_bar: false

forecast_dates:
  start: 2021-07-01
  end: 2022-04-01
  interval: 1mo

plots:
  example_season: "2020/2021"
  example_geos: ["New Jersey"]
  ci_level: 0.95
  n_trajectories: 20

# diagnostics are not produced by default
diagnostics:
  forecast_dates: [2021-07-01]
  models: [LPLModel]
  plots: [posterior_density_plot, parameter_trace_plot]
  tables: [print_posterior_dist, print_model_summary]
