# results will be placed in output/RUN_ID/
run_id: vignette

season:
  start_month: 7 # July
  start_day: 1
  end_month: 4 # April
  end_day: 1
  # use only a few years of data
  first_year: 2018
  last_year: 2022

# prediction features
groups: [season, geography, season_geo]

# include only these geographies
geographies: [Alaska, Connecticut, District of Columbia, Nevada, New Jersey]

models:
  - name: LPLModel
    seed: 42
    model_params:
      muA_shape1: 100.0
      muA_shape2: 180.0
      sigmaA_rate: 80.0
      tau_shape1: 100.0
      tau_shape2: 225.0
      K_shape: 150.0
      K_rate: 6.0
      muM_shape: 2.0
      muM_rate: 25.0
      sigmaM_rate: 80.0
      D_shape: 1000
      D_rate: 3.0

mcmc:
  num_warmup: 500
  num_samples: 500
  num_chains: 4
  progress_bar: false

forecast_dates:
  # run forecasts starting Oct, Nov, Dec
  start: 2021-10-01
  end: 2021-12-01
  interval: 1mo

plots:
  example_season: "2020/2021"
  example_geos: ["New Jersey"]
  ci_level: 0.95
  n_trajectories: 20

# diagnostics are not produced by default
diagnostics:
  forecast_dates: [2021-07-01]
  models: [LPLModel]
  plots: [posterior_density_plot, parameter_trace_plot]
  tables: [print_posterior_dist, print_model_summary]
